#!/usr/bin/env python3
"""Build the Oxford Nanopore SQK-LSK114 ligation schematic."""
from __future__ import annotations
import sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE)); sys.path.insert(0, str(HERE.parents[1] / "lib"))

import nanopore_ligation as N
from chemdraw import Row, annotation_rows, oligo, panel
from page import head, info

OUT = HERE.parent / "nanopore-ligation-v14.html"


def render() -> str:
    lib = N.final_library()
    return "\n".join([head("Oxford Nanopore ligation sequencing V14"), '<div class="wrap">',
        '<h1>Oxford Nanopore ligation sequencing V14 &mdash; SQK-LSK114</h1>',
        '<p class="research-notes"><a href="01_nanopore-ligation-v14.html">Research notes</a></p>',
        info('Commercial protocol: Oxford Nanopore <a href="https://nanoporetech.com/resources/technique/whole-genome-sequencing/document/genomic-dna-by-ligation-sqk-lsk114">GDE_9161_v114 Rev AC</a>.'),
        '<h2>Repair and dA-tail the DNA</h2>',
        '<h3>(1) Repair damage, polish both ends, phosphorylate 5′ ends, and add one 3′ dA</h3>',
        panel(N.end_prep_scene().rows(), cls="small", caption="Both ends are generated by the shared end-prep model; the two 3′ dA overhangs lie on opposite strands."),
        '<h2>Ligate the motor-loaded sequencing adapter</h2>',
        '<h3>(2) The disclosed LA duplex has one complementary 3′ dT</h3>',
        '<seq>' + oligo("LA top", [N.seg("LA top", N.LA_TOP, "r1")])
        + oligo("LA bottom", [N.seg("LA bottom", N.LA_BOTTOM, "r1")]) + '</seq>',
        panel(N.adapter_scene().rows(), cls="small", caption="The two published oligos make a 27-bp duplex plus one 3′ dT. The complete Y-shaped leader and motor attachment are not disclosed."),
        '<h3>(3) Salt-T4 ligase adapts both ends</h3>',
        panel([*N.final_scene().rows(), *annotation_rows(lib)], cls="long", caption="Each dT pairs with an insert dA. ** marks the sealed adapter–insert boundaries. The bracketed motor-loaded leader is a named proprietary structure, not invented bases."),
        '<h2>Sequencing entry</h2>',
        info('No sequencing primer binds this library. A motor on a ligation adapter engages a pore, unzips the duplex, and controls passage of one intact strand. Either adapted end may be captured; the current motor identity, attachment site, full leader sequence, and exact strand polarity are undisclosed.'),
        panel([Row(chunks=[("[flow-cell tether at membrane]   pore | motor -> one DNA strand through nanopore", None, False)]),
               Row(chunks=[("                              no sequencing primer", None, False)])],
              cls="small", caption="The flow-cell tether is supplied during flow-cell priming; the vendor does not establish it as a covalent DNA segment."),
        '</div>'])


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}  ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__": main()
